version: '3.8'

services:
  redis-node-1:
    image: redis:7.2
    command: ["redis-server", "/redis.conf"]
    volumes:
      - ./redis/redis.conf:/redis.conf
    ports:
      - "7001:7001"
      - "17001:17001"  # cluster bus port

  redis-node-2:
    image: redis:7.2
    command: ["redis-server", "/redis.conf"]
    volumes:
      - ./redis/redis.conf:/redis.conf
    ports:
      - "7002:7002"
      - "17002:17002"

  redis-node-3:
    image: redis:7.2
    command: ["redis-server", "/redis.conf"]
    volumes:
      - ./redis/redis.conf:/redis.conf
    ports:
      - "7003:7003"
      - "17003:17003"

  redis-node-4:
    image: redis:7.2
    command: ["redis-server", "/redis.conf"]
    volumes:
      - ./redis/redis.conf:/redis.conf
    ports:
      - "7004:7004"
      - "17004:17004"

  redis-node-5:
    image: redis:7.2
    command: ["redis-server", "/redis.conf"]
    volumes:
      - ./redis/redis.conf:/redis.conf
    ports:
      - "7005:7005"
      - "17005:17005"

  redis-node-6:
    image: redis:7.2
    command: ["redis-server", "/redis.conf"]
    volumes:
      - ./redis/redis.conf:/redis.conf
    ports:
      - "7006:7006"
      - "17006:17006"
